---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc
  labels:
    appname: appname-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 5Gi
