---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc2
  annotations:
    volume.beta.kubernetes.io/storage-class: ocs-storagecluster-ceph-rbd
  labels:
    appname: busybox
    placement: busybox-placement-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
