---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc-3
  labels:
    appname: appname-2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 30Gi
