apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: appname-3
  name: busybox-pvc-81
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 21Gi
  storageClassName: ocs-storagecluster-ceph-rbdmirror
