apiVersion: v1
kind: Pod
metadata:
  labels:
    appname: appname-3
  name: busybox-97
spec:
  containers:
  - command:
    - sh
    - -c
    - while true; do echo $(date) | tee -a /mnt/test/outfile; sync; sleep 4; done
    image: quay.io/vcppds7878/busybox:latest
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: /mnt/test
      name: mypvc
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: busybox-pvc-97
      readOnly: false
