---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pvc-5
  labels:
    appname: appname-2
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbdmirror
  resources:
    requests:
      storage: 250Gi
