---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg1-pvc2
spec:
  accessModes:
    - ReadWriteMany
  # Customize in your overlay.
  storageClassName: rook-cephfs1
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg2-pvc1
spec:
  accessModes:
    - ReadWriteMany
  # Customize in your overlay.
  storageClassName: rook-cephfs2
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-cg2-pvc2
spec:
  accessModes:
    - ReadWriteMany
  # Customize in your overlay.
  storageClassName: rook-cephfs2
  resources:
    requests:
      storage: 4Gi