apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: app-2
  namespace: workload-2
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - app-2
